require("options")
require("diagnostics")
require("lsp")
require("colorscheme")

require("plugins.mini")
require("plugins.snacks")
-- require("plugins.smartsplits")
require("plugins.conform")
require("plugins.blink")
require("plugins.bufferline")
require("plugins.noice")
require("plugins.whichkey")
require("plugins.lualine")
require("plugins.trouble")

require("keymaps")
require("autocmds")
