vim.lsp.enable("basedpyright")
vim.lsp.enable("bash_ls")
vim.lsp.enable("biome")
vim.lsp.enable("clangd")
vim.lsp.enable("cssls")
vim.lsp.enable("fish_lsp")
vim.lsp.enable("gleam")
vim.lsp.enable("gopls")
vim.lsp.enable("hls")
vim.lsp.enable("just")
vim.lsp.enable("lua_ls")
vim.lsp.enable("nixd")
vim.lsp.enable("nushell")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("tailwindcss")
vim.lsp.enable("zls")

-- LSP Keymaps
vim.keymap.set("n", "<leader>lO", function()
	require("otter").activate()
end, { desc = "Force Otter" })

vim.keymap.set("n", "[d", "<cmd>lua vim.diagnostic.goto_prev()<cr>", { desc = "Previous Diagnostic" })
vim.keymap.set("n", "[e", "<cmd>Lspsaga diagnostic_jump_prev<cr>", { desc = "Jump Prev Diagnostic" })
vim.keymap.set("n", "]d", "<cmd>lua vim.diagnostic.goto_next()<cr>", { desc = "Next Diagnostic" })
vim.keymap.set("n", "]e", "<cmd>Lspsaga diagnostic_jump_next<cr>", { desc = "Jump Next Diagnostic" })
vim.keymap.set("n", "<C-s-k>", "<cmd>lua vim.lsp.buf.signature_help()<cr>", { desc = "Signature Help" })
vim.keymap.set("n", "<leader>l.", "<cmd>Lspsaga show_line_diagnostics<cr>", { desc = "Line Diagnostics" })
vim.keymap.set("n", "<leader>la", "<cmd>Lspsaga code_action<cr>", { desc = "Code Action" })
vim.keymap.set("n", "<leader>lD", "<cmd>lua Snacks.picker.lsp_definitions()<cr>", { desc = "Definitions list" })
vim.keymap.set("n", "<leader>lf", function()
	require("conform").format()
end, { desc = "Format file" })
vim.keymap.set("n", "<leader>li", "<cmd>LspInfo<cr>", { desc = "LSP Info" })
vim.keymap.set("n", "<leader>lo", "<cmd>Lspsaga outline<cr>", { desc = "Outline" })
vim.keymap.set("n", "<leader>lq", "<cmd>LspStop<Enter>", { desc = "Stop LSP" })
vim.keymap.set("n", "<leader>lR", "<cmd>LspRestart<Enter>", { desc = "Restart LSP" })
vim.keymap.set("n", "<leader>lr", "<cmd>Lspsaga rename ++project<cr>", { desc = "Rename" })
vim.keymap.set("n", "<leader>ls", "<cmd>lua Snacks.picker.lsp_symbols()<cr>", { desc = "LSP Symbols" })
vim.keymap.set("n", "<leader>lS", "<cmd>LspStart<Enter>", { desc = "Start LSP" })
vim.keymap.set("n", "<leader>lw", "<cmd>Lspsaga show_workspace_diagnostics<cr>", { desc = "Workspace Diagnostics" })
vim.keymap.set("n", "gd", "<cmd>Lspsaga goto_definition<cr>", { desc = "Definitions" })
vim.keymap.set("n", "gpd", "<cmd>Lspsaga peek_definition<cr>", { desc = "Peek Definition" })
vim.keymap.set("n", "gpt", "<cmd>Lspsaga peek_type_definition<cr>", { desc = "Peek Type Definition" })
vim.keymap.set("n", "gt", "<cmd>Lspsaga goto_type_definition<cr>", { desc = "Type Definitions" })
vim.keymap.set("n", "K", function()
	vim.cmd("Lspsaga hover_doc")
end, { desc = "Hover Doc" })
vim.keymap.set("v", "<leader>lf", function()
	require("conform").format()
end, { desc = "Format File" })
vim.keymap.set("x", "<leader>lf", function()
	require("conform").format()
end, { desc = "Format File" })
